config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  get '/', to: 'sessions#new'
  get '/auth/github', as: :github_login
  get '/auth/github/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

# is all the info displayed on same page and page reloaded
# or separate pages for separate info
#resources :users, only: :show do
  get '/my-profile', to: 'users#show'
  get '/recent-activity', to: 'activity#index'
  get '/following', to: 'following#index'
  get '/organizations', to: 'organizations#index'
  get '/repos', to: 'repos#index'
  #end
  # resources :users do
  #   member do
  #     get 'profile'
  #   end
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile
  attr_reader :followers,
              :following,
              :profile_picture,
              :num_starred_repos,
              :recent_activity,
              :organizations,
              :github_attributes

  def initialize(current_user)
    @github_attributes = GithubService.new(current_user)
    @profile_picture = current_user.profile_picture
    @organizations = github_attributes.get_user_organizations
  end

  def following
    response_hash = @github_attributes.get_user_following
    response_hash.map {|user| user[:login] }
  end

  def activity
    recent_activity = @github_attributes.get_user_activity
    recent_activity.map {|action| action[:type]}
  end

  def followers
    followers = @github_attributes.get_user_followers
    followers.map {|user| user[:login]}
  end

  def num_starred_repos
    @github_attributes.get_starred_repos.count
  end
end

app/models/user.rb
class User < ApplicationRecord
  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid                = auth_info.uid
      new_user.name               = auth_info.extra.raw_info.name
      new_user.username           = auth_info.extra.raw_info.login
      new_user.oauth_token        = auth_info.credentials.token
      new_user.oauth_token_secret = auth_info.credentials.secret
      new_user.profile_picture    = auth_info.extra.raw_info.avatar_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end

    redirect_to my_profile_path(user)
  end

  def destroy
    reset_session
    redirect_to root_path
  end

  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @profile = Profile.new(current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
  <% if current_user %>

    <h1 class="navbar-brand mb-0"> Hello, <%= current_user.name %>. You're already logged in.</h1>
    <h1 class="navbar-brand mb-0"> <%= link_to "Profile", my_profile_path(current_user) %> </h1>
    <h1 class="navbar-brand mb-0"> <%= link_to "Logout", logout_path, method: :delete %></h1>
  <% else %>
    <h1 class="navbar-brand mb-0"> <%= link_to "Login with Github", github_login_path %></h1>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApicuriousGithub</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h3> Welcome, <%=current_user.username %>!! </h3>

<%= image_tag(@profile.profile_picture) %><br><br>

<div class="followers">
  <table style= "table-layout: fixed; width: 100%;border-collapse: collapse">
    <caption> These members are following you: </caption>
    <thead>
        <tr>
          <th scope='col' > Username: </th>
        </tr>
    </thead>
    <tbody style='letter-spacing: 2px'>
      <% @profile.followers.each do |member| %>
      <tr>
        <td> <%= member %> </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="following">
  <table style= "table-layout: fixed; width: 100%;border-collapse: collapse">
    <caption> You are following these members: </caption>
    <thead>
        <tr>
          <th scope='col' > Username: </th>
        </tr>
    </thead>
    <tbody style='letter-spacing: 2px'>
      <% @profile.following.each do |member| %>
      <tr>
        <td> <%= member %> </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<h3> Num starred repos:</h3>
<%= @profile.num_starred_repos %><br><br>

<h3>My recent activity ids: </h3>
<%= @profile.activity %><br><br>

<h3> My organizations hash: <br> <%= @profile.organizations if @profile.organizations != [] %> </h3>